# Generated by Django 4.2 on 2023-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_engine", "0002_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
