# Generated by Django 4.2 on 2023-09-15 11:21

from django.db import migrations, models
import file_engine.validators


class Migration(migrations.Migration):
    dependencies = [
        ("file_engine", "0003_alter_file_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                default=0,
                upload_to="documents/%Y/%m/%d",
                validators=[file_engine.validators.validate_file_extension],
            ),
            preserve_default=False,
        ),
    ]
